window.PORTFOLIO_DATA = {
  "featured": [
    "tork-brand-guidelines",
    "everyday-confidence-tee-campaign",
    "ai-built-your-app-in-a-weekend",
    "shopify-backend-scaling",
    "turn-visitors-into-customers"
  ],
  "works": [
    {
      "slug": "tork-brand-guidelines",
      "index": "01",
      "title": "Tork Brand Guidelines",
      "category": "brand",
      "type": "Client Work",
      "year": "2024",
      "image": "assets/images/tork-brand-guidelines.webp",
      "client": "Tork",
      "role": "Graphic Designer & Video Editor",
      "deliverables": "Brand guideline system, logo rules, color palette, typography and usage guidance",
      "summary": "A structured identity system created to keep Tork visually consistent across digital communication.",
      "brief": "The project required translating Tork from a logo and scattered visual cues into a practical brand system that other people could actually use.",
      "challenge": "A technology brand needs to feel modern without becoming visually generic. The guideline also had to be structured enough to protect consistency across campaigns, web graphics and presentation material.",
      "approach": "I organized the system around brand principles first, then moved into logo behavior, safe space, color, typography and repeatable applications. The goal was a guideline that explains decisions instead of simply showing attractive pages.",
      "designNotes": [
        "Poppins is used as the primary typeface to keep communication geometric, clean and highly legible.",
        "The palette balances energetic violet/blue tones with darker neutrals and lighter support shades.",
        "Logo safe-zone and usage rules were treated as operational tools, not decorative guideline pages.",
        "The case study presents the full guideline sequence so viewers can judge system thinking, not only a cover image."
      ],
      "outcome": "The result is a more coherent brand foundation that can guide future social content, web assets and campaign design without relying on one-off styling.",
      "gallery": [
        "assets/galleries/tork-brand-guidelines/01.webp",
        "assets/galleries/tork-brand-guidelines/02.webp",
        "assets/galleries/tork-brand-guidelines/03.webp",
        "assets/galleries/tork-brand-guidelines/04.webp",
        "assets/galleries/tork-brand-guidelines/05.webp",
        "assets/galleries/tork-brand-guidelines/06.webp",
        "assets/galleries/tork-brand-guidelines/07.webp",
        "assets/galleries/tork-brand-guidelines/08.webp",
        "assets/galleries/tork-brand-guidelines/09.webp",
        "assets/galleries/tork-brand-guidelines/10.webp",
        "assets/galleries/tork-brand-guidelines/11.webp",
        "assets/galleries/tork-brand-guidelines/12.webp",
        "assets/galleries/tork-brand-guidelines/13.webp",
        "assets/galleries/tork-brand-guidelines/14.webp",
        "assets/galleries/tork-brand-guidelines/15.webp",
        "assets/galleries/tork-brand-guidelines/16.webp",
        "assets/galleries/tork-brand-guidelines/17.webp",
        "assets/galleries/tork-brand-guidelines/18.webp",
        "assets/galleries/tork-brand-guidelines/19.webp",
        "assets/galleries/tork-brand-guidelines/20.webp"
      ],
      "featured": true,
      "orientation": "wide"
    },
    {
      "slug": "shopify-backend-scaling",
      "index": "02",
      "title": "Shopify Backend Scaling",
      "category": "content",
      "type": "Client Work",
      "year": "2026",
      "image": "assets/images/shopify-backend-scaling.webp",
      "client": "Tork / Shah Alam",
      "role": "Graphic Designer",
      "deliverables": "8-slide ecommerce business carousel",
      "summary": "A narrative carousel about growth, backend complexity and the operational cost of scaling ecommerce.",
      "brief": "The content needed to turn an operational ecommerce problem into a sequence that a business audience could understand quickly while scrolling.",
      "challenge": "The subject is technical and text-heavy. If every slide carried the same density or visual weight, the carousel would feel like a document instead of social content.",
      "approach": "I treated each slide as one beat in a story: hook, consequence, operational pressure and solution framing. Large typography, restrained color and deliberate empty space keep the sequence readable.",
      "designNotes": [
        "One idea per slide keeps the story moving.",
        "The opening slide uses a strong business pain point instead of generic ecommerce imagery.",
        "Consistent spacing, type scale and CTA placement create rhythm across the eight slides.",
        "The design stays business-like so the message feels credible rather than overly promotional."
      ],
      "outcome": "The finished carousel presents backend scaling as a clear business story and gives the content a more premium founder-led visual language.",
      "gallery": [
        "assets/galleries/shopify-backend-scaling/01.webp",
        "assets/galleries/shopify-backend-scaling/02.webp",
        "assets/galleries/shopify-backend-scaling/03.webp",
        "assets/galleries/shopify-backend-scaling/04.webp",
        "assets/galleries/shopify-backend-scaling/05.webp",
        "assets/galleries/shopify-backend-scaling/06.webp",
        "assets/galleries/shopify-backend-scaling/07.webp",
        "assets/galleries/shopify-backend-scaling/08.webp"
      ],
      "featured": true,
      "orientation": "portrait"
    },
    {
      "slug": "turn-visitors-into-customers",
      "index": "03",
      "title": "Turn Visitors into Customers",
      "category": "campaign",
      "type": "Client Work",
      "year": "2026",
      "image": "assets/images/turn_visitors.webp",
      "client": "Tork",
      "role": "Graphic Designer",
      "deliverables": "Website conversion campaign visual",
      "summary": "A conversion-focused visual that positions a website as a system that should move people from interest to action.",
      "brief": "The campaign needed to explain one commercial idea immediately: a website is valuable when it helps turn attention into action.",
      "challenge": "The composition had to feel futuristic and premium while still leaving the headline as the main communication device.",
      "approach": "I built the piece around a central high-contrast subject, a clear headline hierarchy and a restrained purple/white environment. Supporting elements reinforce the idea of digital movement without competing with the message.",
      "designNotes": [
        "Headline is the first read, character is the second read, supporting copy is the third.",
        "High contrast keeps the graphic readable in a crowded social feed.",
        "Minimal framing lets the futuristic visual language feel deliberate instead of decorative."
      ],
      "outcome": "The final asset communicates the conversion message quickly and works as a strong anchor inside Tork’s broader digital campaign system.",
      "featured": true,
      "orientation": "portrait"
    },
    {
      "slug": "ai-built-your-app-in-a-weekend",
      "index": "04",
      "title": "AI Built Your App in a Weekend",
      "category": "editorial",
      "type": "Client Work",
      "year": "2026",
      "image": "assets/galleries/ai-built-your-app-in-a-weekend/01.webp",
      "client": "Tork / Shah Alam",
      "role": "Graphic Designer",
      "deliverables": "8-slide AI product-risk carousel",
      "summary": "An editorial carousel about the risks hidden behind fast AI-built software and the difference between generating code and engineering a reliable product.",
      "brief": "The goal was to make a technical product-risk argument feel immediate for founders and non-technical decision makers.",
      "challenge": "Security, architecture, scale and production reliability are abstract ideas. The carousel needed to communicate urgency without falling into fear-based visual clutter.",
      "approach": "I used poster-scale typography, sharp contrast and a controlled slide rhythm. Each page advances the argument from the fast-build promise to the engineering gaps that appear later.",
      "designNotes": [
        "The opening uses a short, provocative claim that can be understood before reading the support line.",
        "Technical concepts are broken into short narrative units rather than long explanation blocks.",
        "The visual system stays consistent so attention goes to the changing idea, not a new layout on every slide."
      ],
      "outcome": "The result is a strong founder-facing content piece that makes a technical warning easier to read, save and discuss.",
      "gallery": [
        "assets/galleries/ai-built-your-app-in-a-weekend/01.webp",
        "assets/galleries/ai-built-your-app-in-a-weekend/02.webp",
        "assets/galleries/ai-built-your-app-in-a-weekend/03.webp",
        "assets/galleries/ai-built-your-app-in-a-weekend/04.webp",
        "assets/galleries/ai-built-your-app-in-a-weekend/05.webp",
        "assets/galleries/ai-built-your-app-in-a-weekend/06.webp",
        "assets/galleries/ai-built-your-app-in-a-weekend/07.webp",
        "assets/galleries/ai-built-your-app-in-a-weekend/08.webp"
      ],
      "featured": true,
      "orientation": "portrait"
    },
    {
      "slug": "everyday-confidence-tee-campaign",
      "index": "05",
      "title": "Everyday Confidence Tee Campaign",
      "category": "campaign",
      "type": "Concept Project",
      "year": "2026",
      "image": "assets/images/everyday_confidence.webp",
      "client": "Fabrilife — Concept",
      "role": "Graphic Designer",
      "deliverables": "Fashion campaign poster and product presentation",
      "summary": "A fashion-led concept that takes a simple T-shirt graphic and presents it as a more expressive lifestyle campaign.",
      "brief": "The objective was to show the apparel artwork in context instead of relying on a flat mockup alone.",
      "challenge": "The product print, model pose and oversized background typography all needed to feel like one campaign composition while the shirt graphic remained readable.",
      "approach": "I built the final poster from the product artwork and a model source image, then used warm lighting, oversized type and directional background shapes to create a stronger fashion mood.",
      "designNotes": [
        "The T-shirt graphic remains the central product detail even inside a busy lifestyle composition.",
        "Warm orange grading unifies the model, product and background.",
        "Oversized copy adds energy without covering the key garment area.",
        "The final image is clearly labeled as a concept project in the portfolio."
      ],
      "outcome": "The final piece feels more like a launch visual than a catalogue mockup and demonstrates product compositing, art direction and campaign presentation.",
      "gallery": [
        "assets/images/everyday_confidence.webp",
        "assets/images/tee_source.webp",
        "assets/images/tee_model_source.webp"
      ],
      "featured": true,
      "orientation": "portrait"
    },
    {
      "slug": "building-products-that-scale",
      "index": "06",
      "title": "Building Products That Scale",
      "category": "campaign",
      "type": "Client Work",
      "year": "2026",
      "image": "assets/images/building_products_scale.webp",
      "client": "Tork",
      "role": "Graphic Designer",
      "deliverables": "LinkedIn / web hero banner",
      "summary": "A credibility-led banner combining a strong scale message, proof points and a human brand figure.",
      "brief": "The banner needed to position Tork as a team that can build ecommerce and EdTech products for growth.",
      "challenge": "Several proof points had to fit into a wide format without competing with the positioning statement.",
      "approach": "I used a landing-page-style hierarchy: message first, proof metrics second, figure third. The black textile texture and violet field keep the banner premium while the white type remains dominant.",
      "designNotes": [
        "Wide-format hierarchy designed for fast scanning.",
        "Metrics are supportive proof, not the primary focal point.",
        "The figure placement creates direction toward the headline."
      ],
      "outcome": "The finished banner communicates experience, scale and technical credibility in a single frame.",
      "orientation": "wide"
    },
    {
      "slug": "better-content-begins",
      "index": "07",
      "title": "Better Content Begins",
      "category": "content",
      "type": "Client Work",
      "year": "2026",
      "image": "assets/images/better_content.webp",
      "client": "Tork",
      "role": "Graphic Designer",
      "deliverables": "Social content campaign visual",
      "summary": "A brand-led content visual combining classical sculpture imagery with a modern digital grid and purple accent language.",
      "brief": "The visual needed to support a simple positioning statement: better brand communication begins with better content.",
      "challenge": "The classical sculpture metaphor could easily feel unrelated to a digital brand if the styling was not unified.",
      "approach": "I used a dark grid, controlled purple glow and the laptop as a modern bridge between classical craft and contemporary content production.",
      "designNotes": [
        "The sculpture creates a distinctive visual hook.",
        "Purple selection-style framing ties the piece to a digital design environment.",
        "The layout leaves enough negative space for the message to stay readable."
      ],
      "outcome": "The piece gives Tork a more distinctive content voice while keeping the message direct.",
      "orientation": "portrait"
    },
    {
      "slug": "tork-sales-machine",
      "index": "08",
      "title": "Your Website Is the Sales Machine",
      "category": "campaign",
      "type": "Client Work",
      "year": "2026",
      "image": "assets/images/tork_sales_machine.webp",
      "client": "Tork",
      "role": "Graphic Designer",
      "deliverables": "Conversion campaign graphic",
      "summary": "A direct-response visual that reframes a website as an active sales system rather than a passive online presence.",
      "brief": "The design had to translate a business idea into a high-contrast square format that could work on social media.",
      "challenge": "The message needed authority without relying on a long explanation or crowded UI mockups.",
      "approach": "I built the hierarchy around a short headline and used a focused web-device visual as evidence. The dark background keeps the presentation compact and premium.",
      "designNotes": [
        "Short copy gives the design immediate clarity.",
        "Device imagery supports the claim instead of replacing it.",
        "Consistent Tork accents connect the visual to the wider campaign system."
      ],
      "outcome": "The result is a compact campaign asset with a clear business takeaway.",
      "orientation": "square"
    },
    {
      "slug": "turn-ideas-into-visuals",
      "index": "09",
      "title": "Turn Your Ideas into Visuals",
      "category": "campaign",
      "type": "Client Work",
      "year": "2026",
      "image": "assets/images/turn_ideas_visuals.webp",
      "client": "Tork",
      "role": "Graphic Designer",
      "deliverables": "Creative services social visual",
      "summary": "A creative-services graphic that turns the idea of imagination becoming visible into a single visual metaphor.",
      "brief": "The post needed to communicate creative transformation in a way that felt more visual than explanatory.",
      "challenge": "A literal “design service” layout would have been easy to ignore.",
      "approach": "I used a surreal subject and screen-based composition to make the transformation idea more memorable, then kept the copy concise so the image does most of the work.",
      "designNotes": [
        "Surreal imagery carries the concept.",
        "Type is intentionally restrained.",
        "Purple and blue tones connect the piece to Tork’s digital identity."
      ],
      "outcome": "The visual communicates a creative-service message with a stronger, more ownable hook.",
      "orientation": "square"
    },
    {
      "slug": "ai-stack-ecommerce",
      "index": "10",
      "title": "AI Stack for Ecommerce Operations",
      "category": "editorial",
      "type": "Client Work",
      "year": "2026",
      "image": "assets/images/ai-stack-ecommerce.webp",
      "client": "Tork / Shah Alam",
      "role": "Graphic Designer",
      "deliverables": "10-slide AI workflow carousel",
      "summary": "A systems-focused carousel mapping how AI can support multiple ecommerce workflow layers while keeping human judgment in the loop.",
      "brief": "The content needed to show a multi-layer AI operating model without turning into a dense process document.",
      "challenge": "Each layer has different responsibilities and human ownership, so the hierarchy needed to remain consistent across ten pages.",
      "approach": "I used one repeated visual structure and changed only the content layer, allowing the viewer to compare the system from slide to slide.",
      "designNotes": [
        "Consistent layer structure reduces cognitive load.",
        "AI responsibilities and human ownership are separated visually.",
        "The sequence builds from workflow detail to a more complete operating model."
      ],
      "outcome": "The final carousel makes a complex operational framework easier to scan and understand.",
      "gallery": [
        "assets/galleries/ai-stack-ecommerce/01.webp",
        "assets/galleries/ai-stack-ecommerce/02.webp",
        "assets/galleries/ai-stack-ecommerce/03.webp",
        "assets/galleries/ai-stack-ecommerce/04.webp",
        "assets/galleries/ai-stack-ecommerce/05.webp",
        "assets/galleries/ai-stack-ecommerce/06.webp",
        "assets/galleries/ai-stack-ecommerce/07.webp",
        "assets/galleries/ai-stack-ecommerce/08.webp",
        "assets/galleries/ai-stack-ecommerce/09.webp",
        "assets/galleries/ai-stack-ecommerce/10.webp"
      ],
      "orientation": "portrait"
    },
    {
      "slug": "underdog-advantage",
      "index": "11",
      "title": "The Underdog Advantage",
      "category": "editorial",
      "type": "Client Work",
      "year": "2026",
      "image": "assets/images/underdog-advantage.webp",
      "client": "Tork / Shah Alam",
      "role": "Graphic Designer",
      "deliverables": "11-slide founder-content carousel",
      "summary": "A founder-content carousel about the strategic advantages smaller teams can have over larger organizations.",
      "brief": "The concept needed to feel sharp, optimistic and useful rather than like generic motivational content.",
      "challenge": "The message depends on a sequence of advantages, so every slide had to feel connected while still carrying its own strong point.",
      "approach": "I used a consistent headline-driven system, compact supporting copy and a restrained business aesthetic to keep the focus on the argument.",
      "designNotes": [
        "The opening establishes the theme quickly.",
        "Each slide uses one dominant claim.",
        "Repeated layout logic gives the carousel a deliberate reading rhythm."
      ],
      "outcome": "The result is a stronger founder-content series with a clear point of view and repeatable visual system.",
      "gallery": [
        "assets/galleries/underdog-advantage/01.webp",
        "assets/galleries/underdog-advantage/02.webp",
        "assets/galleries/underdog-advantage/03.webp",
        "assets/galleries/underdog-advantage/04.webp",
        "assets/galleries/underdog-advantage/05.webp",
        "assets/galleries/underdog-advantage/06.webp",
        "assets/galleries/underdog-advantage/07.webp",
        "assets/galleries/underdog-advantage/08.webp",
        "assets/galleries/underdog-advantage/09.webp",
        "assets/galleries/underdog-advantage/10.webp",
        "assets/galleries/underdog-advantage/11.webp"
      ],
      "orientation": "portrait"
    },
    {
      "slug": "pathfinder-methodology",
      "index": "12",
      "title": "How to Choose the Right Methodology",
      "category": "education",
      "type": "Client Work",
      "year": "2026",
      "image": "assets/images/pathfinder-methodology.webp",
      "client": "Pathfinder Research & Consultancy Center",
      "role": "Graphic Designer",
      "deliverables": "7-slide research education carousel",
      "summary": "A research-education carousel that helps students connect research questions, design choices and data quality.",
      "brief": "The content needed to simplify a topic that students often find abstract and intimidating.",
      "challenge": "Methodology can become overly theoretical. The design needed to stay academically credible while still feeling approachable on social media.",
      "approach": "I structured the seven slides as a decision journey: understand the problem, match the question, evaluate fit and think about data quality.",
      "designNotes": [
        "Short sections reduce academic density.",
        "Numbered progression gives the carousel a teaching rhythm.",
        "Brand styling stays consistent with Pathfinder’s research communication."
      ],
      "outcome": "The finished piece turns methodology selection into a clearer, more practical learning sequence.",
      "gallery": [
        "assets/galleries/pathfinder-methodology/01.webp",
        "assets/galleries/pathfinder-methodology/02.webp",
        "assets/galleries/pathfinder-methodology/03.webp",
        "assets/galleries/pathfinder-methodology/04.webp",
        "assets/galleries/pathfinder-methodology/05.webp",
        "assets/galleries/pathfinder-methodology/06.webp",
        "assets/galleries/pathfinder-methodology/07.webp"
      ],
      "orientation": "portrait"
    },
    {
      "slug": "pathfinder-research-skills",
      "index": "13",
      "title": "Six Core Research Skills",
      "category": "education",
      "type": "Client Work",
      "year": "2026",
      "image": "assets/images/pathfinder_research_skills.webp",
      "client": "Pathfinder Research & Consultancy Center",
      "role": "Graphic Designer",
      "deliverables": "Educational research poster",
      "summary": "A structured visual designed to turn a list of core research capabilities into a cleaner, more memorable learning asset.",
      "brief": "The poster needed to communicate several skills without feeling like a dense academic handout.",
      "challenge": "Multiple ideas compete for attention when everything is given equal visual weight.",
      "approach": "I used a strong title zone, clear modular groupings and controlled brand styling so each skill can be scanned independently.",
      "designNotes": [
        "Clear educational hierarchy.",
        "Consistent icon/section treatment.",
        "Designed for both social viewing and saved reference."
      ],
      "outcome": "The final poster is easier to scan and more visually aligned with Pathfinder’s educational identity.",
      "orientation": "portrait"
    },
    {
      "slug": "academic-excellence",
      "index": "14",
      "title": "Academic Excellence Through Research",
      "category": "education",
      "type": "Client Work",
      "year": "2026",
      "image": "assets/images/academic_excellence.webp",
      "client": "Pathfinder Research & Consultancy Center",
      "role": "Graphic Designer",
      "deliverables": "University event promotional poster",
      "summary": "A university-facing event visual connecting research training with academic development and opportunity.",
      "brief": "The poster needed to make an academic session feel current, useful and credible to students.",
      "challenge": "The information hierarchy had to handle event identity, theme and institutional context without becoming poster-like clutter.",
      "approach": "I prioritized the event title and learning promise, then organized support information into quieter layers.",
      "designNotes": [
        "Academic tone without looking bureaucratic.",
        "High-contrast hierarchy for mobile viewing.",
        "Institutional elements stay secondary to the event message."
      ],
      "outcome": "The final asset gives the program a more professional, student-facing visual identity.",
      "orientation": "portrait"
    },
    {
      "slug": "bkash-cashout-concept",
      "index": "15",
      "title": "bKash Cash-Out Campaign",
      "category": "campaign",
      "type": "Concept Project",
      "year": "2026",
      "image": "assets/images/bkash_1.webp",
      "client": "bKash — Concept",
      "role": "Graphic Designer",
      "deliverables": "Bangla fintech advertising visual",
      "summary": "A local-market advertising concept built around familiar fintech behavior and high-visibility Bangla communication.",
      "brief": "The objective was to explore how a mobile financial service campaign could feel energetic and culturally familiar.",
      "challenge": "Fintech ads need trust, simplicity and instant recognition while still standing out in a busy local feed.",
      "approach": "I used bold brand-color contrast, a direct Bangla headline and a clear human focal point to keep the message accessible.",
      "designNotes": [
        "Bangla-first communication.",
        "Brand-color dominance supports recognition.",
        "Human expression gives the campaign immediate energy."
      ],
      "outcome": "The concept demonstrates local advertising hierarchy and commercial social design.",
      "orientation": "square"
    },
    {
      "slug": "bkash-digital-payment-concept",
      "index": "16",
      "title": "bKash Digital Payment Visual",
      "category": "campaign",
      "type": "Concept Project",
      "year": "2026",
      "image": "assets/images/bkash_2.webp",
      "client": "bKash — Concept",
      "role": "Graphic Designer",
      "deliverables": "Fintech promotional concept",
      "summary": "A second fintech concept exploring a different promotional composition for mobile payment communication.",
      "brief": "The task was to keep the service message clear while testing a more promotional, offer-led visual structure.",
      "challenge": "Offer graphics can become crowded quickly when product, person and copy all compete.",
      "approach": "I used one dominant focal point, grouped the offer information and kept the supporting decorative elements behind the main message.",
      "designNotes": [
        "Offer-first hierarchy.",
        "Strong local commercial color language.",
        "Designed for fast mobile scanning."
      ],
      "outcome": "The final concept works as a punchy local promotional asset while staying readable.",
      "orientation": "square"
    },
    {
      "slug": "cerave-clean-skin",
      "index": "17",
      "title": "CeraVe Clean Skin Campaign",
      "category": "product",
      "type": "Concept Project",
      "year": "2026",
      "image": "assets/images/cerave_clean_skin.webp",
      "client": "CeraVe — Concept",
      "role": "Graphic Designer",
      "deliverables": "Skincare product advertising visual",
      "summary": "A skincare advertising concept focused on clean product presentation, freshness and dermatology-led trust.",
      "brief": "The goal was to create a more premium product visual using familiar skincare advertising cues without overloading the composition.",
      "challenge": "Product ads often lose clarity when effects and environment become stronger than the product itself.",
      "approach": "I kept the package as the hero, used controlled lighting and a clean visual environment, and limited supporting copy to preserve premium product focus.",
      "designNotes": [
        "Product remains the dominant focal point.",
        "Clean lighting supports skincare trust cues.",
        "Minimal copy keeps the composition commercial rather than editorial."
      ],
      "outcome": "The result is a cleaner, more premium skincare concept suitable for digital advertising.",
      "orientation": "portrait"
    },
    {
      "slug": "amazon-travel-smart",
      "index": "20",
      "title": "Travel Light, Travel Smart",
      "category": "product",
      "type": "Concept Project",
      "year": "2026",
      "image": "assets/images/amazon_3.webp",
      "client": "Amazon — Concept",
      "role": "Graphic Designer",
      "deliverables": "Travel backpack ecommerce visual",
      "summary": "A clean ecommerce concept presenting a travel backpack around portability, function and everyday use.",
      "brief": "The product needed to feel lightweight and practical while still looking premium enough for a marketplace ad.",
      "challenge": "A bag has many details that can be lost when the composition becomes too decorative.",
      "approach": "I used a pale blue environment, large product scale and small functional callouts to keep features visible.",
      "designNotes": [
        "Soft environment supports a travel/lifestyle feel.",
        "Feature callouts stay secondary to the product.",
        "Balanced whitespace keeps the design light."
      ],
      "outcome": "The concept shows practical product storytelling without crowding the frame.",
      "orientation": "square"
    },
    {
      "slug": "food-ice-cream",
      "index": "21",
      "title": "Chocolate Ice Cream Campaign",
      "category": "product",
      "type": "Concept Project",
      "year": "2026",
      "image": "assets/images/food_1.webp",
      "client": "Food Brand — Concept",
      "role": "Graphic Designer",
      "deliverables": "Food advertising visual",
      "summary": "A high-energy food ad concept built around texture, movement and indulgence.",
      "brief": "The objective was to make the product feel rich and immediately appetizing in a static graphic.",
      "challenge": "Food visuals need enough motion and texture to create appetite without making the composition messy.",
      "approach": "I used splashes, chocolate tones and a centered hero treatment to exaggerate richness while keeping the product readable.",
      "designNotes": [
        "Texture is used as the main appetite cue.",
        "Centered product keeps the composition controlled.",
        "High contrast supports social-feed impact."
      ],
      "outcome": "The final concept feels energetic, commercial and product-forward.",
      "orientation": "portrait"
    },
    {
      "slug": "food-pizza",
      "index": "22",
      "title": "Pizza Promotional Visual",
      "category": "product",
      "type": "Concept Project",
      "year": "2026",
      "image": "assets/images/food_2.webp",
      "client": "Food Brand — Concept",
      "role": "Graphic Designer",
      "deliverables": "Pizza advertising visual",
      "summary": "A bold pizza concept using warm colors and a top-down product arrangement to create immediate appetite appeal.",
      "brief": "The graphic needed to look fast, fun and commercial without relying on a human model.",
      "challenge": "Top-down food layouts can feel flat if the surrounding graphics lack depth.",
      "approach": "I used warm tonal layers, angled accents and strong central product scale to create motion around the pizza.",
      "designNotes": [
        "Warm palette reinforces appetite appeal.",
        "Top-down product remains the clear hero.",
        "Geometric accents add pace without covering the food."
      ],
      "outcome": "The result is a strong, simple promotional visual suitable for food social content.",
      "orientation": "landscape"
    },
    {
      "slug": "food-hotdog",
      "index": "23",
      "title": "Hot Dog Promotional Visual",
      "category": "product",
      "type": "Concept Project",
      "year": "2026",
      "image": "assets/images/food_3.webp",
      "client": "Food Brand — Concept",
      "role": "Graphic Designer",
      "deliverables": "Fast-food advertising visual",
      "summary": "A colorful fast-food concept designed around instant product recognition and playful energy.",
      "brief": "The goal was to create a high-impact ad that reads immediately on mobile.",
      "challenge": "Food and headline both need space in a small square canvas.",
      "approach": "I separated the product and copy zones clearly, then used high-saturation accents to keep the composition lively.",
      "designNotes": [
        "Clear product/copy separation.",
        "Bright commercial palette.",
        "Designed for fast mobile recognition."
      ],
      "outcome": "The concept demonstrates direct-response food advertising structure.",
      "orientation": "square"
    },
    {
      "slug": "food-burger",
      "index": "24",
      "title": "Burger Special Campaign",
      "category": "product",
      "type": "Concept Project",
      "year": "2026",
      "image": "assets/images/food_4.webp",
      "client": "Food Brand — Concept",
      "role": "Graphic Designer",
      "deliverables": "Burger promotional poster",
      "summary": "A bold burger promotion using oversized product photography and high-contrast offer styling.",
      "brief": "The visual needed to make the burger feel substantial while communicating a promotional message quickly.",
      "challenge": "Too many offer graphics can reduce appetite appeal.",
      "approach": "I kept the burger dominant, limited the text and used warm brand-like tones to support the product.",
      "designNotes": [
        "Oversized product scale.",
        "Offer copy stays secondary.",
        "Warm palette keeps appetite appeal strong."
      ],
      "outcome": "The final concept is straightforward, commercial and easy to understand at a glance.",
      "orientation": "square"
    },
    {
      "slug": "gaming-fc",
      "index": "25",
      "title": "Football Game Promotional Visual",
      "category": "gaming",
      "type": "Concept Project",
      "year": "2026",
      "image": "assets/images/gaming_1.webp",
      "client": "Gaming — Concept",
      "role": "Graphic Designer",
      "deliverables": "Game launch/promotional visual",
      "summary": "A game-promotion concept built around dramatic character energy and a premium dark visual environment.",
      "brief": "The goal was to create a gaming poster that feels like launch marketing rather than a simple game screenshot.",
      "challenge": "Multiple game elements can make the composition noisy quickly.",
      "approach": "I used one dominant key visual, dark contrast and controlled supporting elements to create a clearer hierarchy.",
      "designNotes": [
        "Hero visual first.",
        "Dark cinematic grading.",
        "Compact promotional copy."
      ],
      "outcome": "The result feels closer to campaign art than a generic gaming poster.",
      "orientation": "square"
    },
    {
      "slug": "gaming-racing",
      "index": "26",
      "title": "Racing Game Promotional Visual",
      "category": "gaming",
      "type": "Concept Project",
      "year": "2026",
      "image": "assets/images/gaming_2.webp",
      "client": "Gaming — Concept",
      "role": "Graphic Designer",
      "deliverables": "Gaming social poster",
      "summary": "A high-speed gaming visual built to communicate movement and competitive energy.",
      "brief": "The concept needed to feel fast before the viewer reads any copy.",
      "challenge": "Static graphics have to imply motion through composition and lighting alone.",
      "approach": "I used diagonal direction, contrast and motion-led framing to create a sense of speed.",
      "designNotes": [
        "Diagonal composition.",
        "High-contrast lighting.",
        "Minimal copy to preserve energy."
      ],
      "outcome": "The concept reads quickly and carries a stronger sense of movement.",
      "orientation": "square"
    },
    {
      "slug": "gaming-rpg",
      "index": "27",
      "title": "RPG Game Feature Visual",
      "category": "gaming",
      "type": "Concept Project",
      "year": "2026",
      "image": "assets/images/gaming_3.webp",
      "client": "Gaming — Concept",
      "role": "Graphic Designer",
      "deliverables": "RPG promotional graphic",
      "summary": "A fantasy/action gaming concept focused on atmosphere, character recognition and feature framing.",
      "brief": "The layout needed to organize multiple game details without losing the main visual.",
      "challenge": "Feature-heavy gaming ads can feel like a collage if hierarchy is weak.",
      "approach": "I used a strong title area, grouped feature information and a single dominant environment to unify the composition.",
      "designNotes": [
        "Information grouped into deliberate zones.",
        "Atmospheric art carries the mood.",
        "Feature copy is secondary to key art."
      ],
      "outcome": "The concept balances game atmosphere with promotional information more effectively.",
      "orientation": "square"
    },
    {
      "slug": "gaming-action",
      "index": "28",
      "title": "Action Game Promotional Visual",
      "category": "gaming",
      "type": "Concept Project",
      "year": "2026",
      "image": "assets/images/gaming_4.webp",
      "client": "Gaming — Concept",
      "role": "Graphic Designer",
      "deliverables": "Action-game social creative",
      "summary": "A cinematic gaming creative built around a bold action tone and strong key-art treatment.",
      "brief": "The goal was to create a scroll-stopping game visual suitable for social promotion.",
      "challenge": "The visual needed intensity without destroying readability.",
      "approach": "I kept the key art large, used strong tonal grading and constrained the copy to a few high-priority elements.",
      "designNotes": [
        "Cinematic key art.",
        "High-impact tonal grading.",
        "Focused promotional hierarchy."
      ],
      "outcome": "The final concept feels energetic while staying easy to scan.",
      "orientation": "square"
    },
    {
      "slug": "fifa-final-match-poster",
      "index": "29",
      "title": "Argentina vs Spain Final",
      "category": "sports",
      "type": "Concept Project",
      "year": "2026",
      "image": "assets/images/fifa_final.webp",
      "client": "Sports — Concept",
      "role": "Graphic Designer",
      "deliverables": "Football final event poster",
      "summary": "A dramatic match poster centered on rivalry, national identity and the importance of a final.",
      "brief": "The poster needed to feel like a major final, not a routine match announcement.",
      "challenge": "Two superstar portraits, national flags, venue and event time all needed space without competing.",
      "approach": "I used a face-off composition with a central information spine and stadium anchor, then pushed the grading toward a deep tournament-night atmosphere.",
      "designNotes": [
        "Rivalry drives the composition.",
        "Central spine organizes flags and match details.",
        "Stadium base gives the poster event scale.",
        "Clearly presented as a concept project."
      ],
      "outcome": "The final poster feels high-stakes and communicates the event structure in one glance.",
      "orientation": "portrait"
    },
    {
      "slug": "side-effect-of-blame-thumbnail",
      "index": "30",
      "title": "The Side Effect of Blame",
      "category": "thumbnail",
      "type": "Client Work",
      "year": "2026",
      "image": "assets/images/side_effect_blame.webp",
      "client": "YouTube Content Creator",
      "role": "Graphic Designer",
      "deliverables": "YouTube thumbnail composite",
      "summary": "A dramatic thumbnail built around pressure, accusation and a bilingual title.",
      "brief": "The thumbnail needed to communicate conflict instantly at small size.",
      "challenge": "The emotional story had to read before the viewer processes the text.",
      "approach": "I centered the subject, framed him with pointing hands and replaced the neutral background with a red, high-pressure environment. The title was positioned close to the face so emotion and topic stay connected.",
      "designNotes": [
        "Pointing hands create narrative direction toward the subject.",
        "Red/orange grading increases emotional tension.",
        "Bilingual text is large enough for mobile thumbnail viewing.",
        "Source images are shown in the case study to make the compositing process visible."
      ],
      "outcome": "The final thumbnail communicates conflict faster and has a stronger small-screen silhouette.",
      "gallery": [
        "assets/images/side_effect_blame.webp",
        "assets/images/thumb_room.webp",
        "assets/images/thumb_portrait.webp",
        "assets/images/thumb_hands.webp"
      ],
      "orientation": "wide"
    },
    {
      "slug": "ai-vocabulary",
      "index": "31",
      "title": "AI Vocabulary — 20 Terms",
      "category": "editorial",
      "type": "Editorial / Infographic",
      "year": "2026",
      "image": "assets/images/editorial_1.webp",
      "client": "Educational Content",
      "role": "Graphic Designer",
      "deliverables": "AI terminology infographic",
      "summary": "A structured explainer designed to make common AI terminology easier for non-specialist readers.",
      "brief": "The task was to fit twenty definitions into a single visual without making it feel like a wall of text.",
      "challenge": "Information density was the main design problem.",
      "approach": "I used a predictable grid, consistent numbering and small icon accents so the viewer can scan the page in sections rather than reading it as one block.",
      "designNotes": [
        "Repeatable grid improves scanability.",
        "Consistent numbering creates structure.",
        "Soft accent icons separate concepts without adding visual noise."
      ],
      "outcome": "The infographic turns a dense topic into a more approachable saved-reference asset.",
      "orientation": "portrait"
    },
    {
      "slug": "system-architecture-cases",
      "index": "32",
      "title": "System Architecture Case Studies",
      "category": "editorial",
      "type": "Editorial / Infographic",
      "year": "2026",
      "image": "assets/images/editorial_2.webp",
      "client": "Educational Content",
      "role": "Graphic Designer",
      "deliverables": "System architecture learning infographic",
      "summary": "A concentric information graphic mapping technology systems from simpler cases toward larger-scale architecture problems.",
      "brief": "The visual needed to show progression and complexity while keeping many examples legible.",
      "challenge": "A flat list would not communicate the relationship between scale and system complexity.",
      "approach": "I used concentric rings as the core information model, placing examples by relative complexity and keeping the explanatory text outside the main shapes where possible.",
      "designNotes": [
        "Concentric structure communicates progression.",
        "Blue tonal system keeps the information calm.",
        "Examples are distributed spatially rather than stacked in a list."
      ],
      "outcome": "The final graphic makes an abstract architecture-learning path easier to visualize.",
      "orientation": "portrait"
    },
    {
      "slug": "perfect-product-page",
      "index": "33",
      "title": "Anatomy of a Perfect Product Page",
      "category": "editorial",
      "type": "Editorial / Infographic",
      "year": "2026",
      "image": "assets/images/editorial_3.webp",
      "client": "Ecommerce Education",
      "role": "Graphic Designer",
      "deliverables": "Ecommerce product-page infographic",
      "summary": "A long-form ecommerce infographic breaking down the structure of a high-converting product page.",
      "brief": "The objective was to turn a detailed ecommerce checklist into one visual reference.",
      "challenge": "The content includes many sections, so poor hierarchy would make the graphic unusable.",
      "approach": "I used a wireframe-style page skeleton with labels positioned around the layout, allowing each recommendation to point to a specific part of the product page.",
      "designNotes": [
        "Wireframe gives the viewer a spatial reference.",
        "Side annotations keep long explanations outside the core page.",
        "Green highlight blocks are used sparingly for action-oriented elements."
      ],
      "outcome": "The result works as both an educational poster and a practical ecommerce checklist.",
      "orientation": "portrait"
    },
    {
      "slug": "ui-vs-ux",
      "index": "34",
      "title": "UI vs UX",
      "category": "editorial",
      "type": "Editorial / Infographic",
      "year": "2026",
      "image": "assets/images/editorial_4.webp",
      "client": "Design Education",
      "role": "Graphic Designer",
      "deliverables": "UI/UX explainer visual",
      "summary": "A clean design-education graphic separating how an interface looks from how an experience works and feels.",
      "brief": "The content needed to explain a common design distinction without becoming textbook-like.",
      "challenge": "UI and UX overlap, so the visual had to separate them clearly while still showing that they belong to one product experience.",
      "approach": "I split the composition into two conceptual zones and used the phone mockup as the bridge between interface and experience.",
      "designNotes": [
        "Large UI/UX labels establish instant comparison.",
        "Phone mockup connects the two concepts visually.",
        "Purple system keeps the piece modern and cohesive."
      ],
      "outcome": "The final visual makes a basic design concept easier to communicate and remember.",
      "orientation": "square"
    }
  ],
  "videos": [
    {
      "slug": "talking-head-client-edit",
      "index": "V01",
      "title": "Talking-Head Client Edit",
      "type": "Client Work",
      "year": "2026",
      "orientation": "landscape",
      "poster": "assets/posters/talking_head.jpg",
      "video": "assets/videos/talking_head.mp4",
      "client": "Research & Education Client",
      "role": "Video Editor",
      "deliverables": "Talking-head edit, pacing, text support and visual emphasis",
      "summary": "A speaker-led client edit focused on clarity, pacing and professional presentation.",
      "brief": "The footage needed to feel more active without letting effects distract from the speaker or the information.",
      "challenge": "Talking-head content can become visually static, but excessive motion can reduce trust and make educational material harder to follow.",
      "approach": "I tightened pacing, used supporting graphic moments only where they help comprehension and kept transitions restrained.",
      "designNotes": [
        "Speaker remains the primary focus.",
        "Cuts and text emphasis are timed to information changes.",
        "Motion is used as support, not decoration."
      ],
      "outcome": "The final edit feels cleaner, more structured and more suitable for professional educational content."
    },
    {
      "slug": "podcast-client-edit",
      "index": "V02",
      "title": "Podcast Client Edit",
      "type": "Client Work · American Client",
      "year": "2026",
      "orientation": "landscape",
      "poster": "assets/posters/podcast.jpg",
      "video": "assets/videos/podcast.mp4",
      "client": "American-Bangladeshi Podcast Client",
      "role": "Video Editor",
      "deliverables": "Podcast editing, branded graphics, pacing and short-form-ready moments",
      "summary": "A client podcast edit designed to improve long-form viewing and make the content easier to repurpose.",
      "brief": "The podcast needed a cleaner visual rhythm while preserving the natural conversation and speaker chemistry.",
      "challenge": "Long-form discussion can feel static if every minute has the same visual treatment.",
      "approach": "I used purposeful cut changes, branded support graphics and restrained motion to create variation without interrupting the conversation.",
      "designNotes": [
        "Long-form pacing comes before flashy transitions.",
        "Brand elements are repeated consistently.",
        "The edit structure supports later short-form repurposing."
      ],
      "outcome": "The final edit feels more polished and platform-ready while retaining the natural pace of the conversation."
    },
    {
      "slug": "short-motion-practice",
      "index": "V03",
      "title": "Short-Form Motion Edit",
      "type": "Practice Work",
      "year": "2026",
      "orientation": "portrait",
      "poster": "assets/posters/short_motion.jpg",
      "video": "assets/videos/short_motion.mp4",
      "client": "Practice Project",
      "role": "Video Editor / Motion Designer",
      "deliverables": "Vertical edit, animated text and motion-led pacing",
      "summary": "A mobile-first practice edit exploring faster rhythm, kinetic typography and motion emphasis.",
      "brief": "The exercise focused on making a short vertical clip feel native to high-attention social platforms.",
      "challenge": "The edit had to be energetic without becoming visually chaotic.",
      "approach": "I used a strong opening, quick pacing, large readable typography and selective motion accents.",
      "designNotes": [
        "Designed for vertical viewing.",
        "Typography remains readable on a phone.",
        "Motion supports the spoken beat and pacing."
      ],
      "outcome": "The piece demonstrates short-form timing and motion experimentation without being presented as client work."
    },
    {
      "slug": "promotional-practice-edit",
      "index": "V04",
      "title": "Promotional Motion Video",
      "type": "Practice Work",
      "year": "2026",
      "orientation": "landscape",
      "poster": "assets/posters/promotional.jpg",
      "video": "assets/videos/promotional.mp4",
      "client": "Practice Project",
      "role": "Video Editor / Motion Designer",
      "deliverables": "Promotional edit, motion graphics and visual transitions",
      "summary": "A practice promotional edit focused on energy, sequencing and commercial-style motion.",
      "brief": "The project was used to explore how motion, transitions and visual timing can build a stronger promotional feel.",
      "challenge": "Promotional edits can easily become effect-heavy and lose message clarity.",
      "approach": "I kept the sequence compact, used transitions only at meaningful visual changes and balanced effects with clean timing.",
      "designNotes": [
        "Commercial pacing without constant effects.",
        "Transitions connect scenes instead of acting as decoration.",
        "Music/visual rhythm drives the sequence."
      ],
      "outcome": "The practice piece demonstrates promotional editing and motion control while staying clearly labeled as non-client work."
    },
    {
      "slug": "dr-bones-youtube-feature",
      "index": "V05",
      "title": "Dr. Bones YouTube Feature",
      "type": "YouTube Channel Work",
      "year": "2026",
      "orientation": "portrait",
      "poster": "assets/posters/dr_bones.jpg",
      "video": "assets/videos/dr_bones.mp4",
      "client": "Dr. Bones YouTube Channel",
      "role": "Video Editor / Creator",
      "deliverables": "YouTube short-form educational edit",
      "summary": "A public-facing YouTube piece added to show channel content alongside client and practice work.",
      "brief": "The edit needed to communicate the topic quickly in a short mobile-first format and feel native to YouTube viewing.",
      "challenge": "Short educational content has to establish context fast while keeping the visual pace alive.",
      "approach": "I used quick changes, readable text moments and a compact structure that prioritizes the first seconds of the video.",
      "designNotes": [
        "Mobile-first framing.",
        "Fast but readable pacing.",
        "Public channel work broadens the video portfolio beyond private client deliverables."
      ],
      "outcome": "The final piece shows a different content environment and adds more range to the motion section.",
      "external": "https://youtube.com/@dr.bones143?si=zQ_Pr3MeU2pC8ydp"
    },
    {
      "slug": "historical-short-edit",
      "index": "V06",
      "title": "Historical Short-Form Edit",
      "type": "Practice Work",
      "year": "2026",
      "orientation": "portrait",
      "poster": "assets/posters/historical_short.jpg",
      "video": "assets/videos/historical_short.mp4",
      "client": "Practice Project",
      "role": "Video Editor / Motion Designer",
      "deliverables": "Vertical short-form edit, pacing, text moments and visual storytelling",
      "summary": "A vertical motion-led edit added to strengthen the compact video grid and show another short-form storytelling sample.",
      "brief": "The goal was to present a dark, high-attention short-form piece that feels cinematic and readable in a mobile-first frame.",
      "challenge": "The footage relies on mood, symbolism and pacing, so the edit needed to stay visually strong without turning confusing or overcrowded.",
      "approach": "I kept the structure compact, used a strong central subject and let timing, contrast and restrained graphic support carry the tone.",
      "designNotes": [
        "Built for mobile-first vertical viewing.",
        "High-contrast mood supports fast attention capture.",
        "Short runtime keeps the edit tight and replayable."
      ],
      "outcome": "The piece adds another distinct short-form sample to the video section while keeping the overall section visually compact."
    }
  ],
  "testimonials": [
    {
      "name": "Research & Education Company",
      "role": "Educational research centre",
      "country": "Bangladesh",
      "image": "assets/logos/pathfinder.webp",
      "service": "Video Editing + Graphic Design",
      "quote": "Working with Ishtiak has been a great experience for our brand. He handled both our video editing and graphic design needs with great attention to detail. He understood our research and educational content and turned it into clear, engaging, and professional visuals. His creativity, communication, and ability to follow our brand style made the entire process smooth. We highly recommend him to anyone looking for a reliable video editor and graphic designer."
    },
    {
      "name": "American Vlogger",
      "role": "Software Engineer at Meta",
      "country": "American-Bangladeshi",
      "image": "assets/images/testimonial_couple.webp",
      "service": "Full Video Editing + Reels",
      "quote": "I had a great experience working with Azmi as my video editor. He handled my long-form vlog videos as well as short-form reels, and consistently delivered clean, engaging edits that matched my style. He was easy to communicate with, understood my vision quickly, and paid attention to the small details that made the videos better. I’m very happy with his work and would definitely recommend him."
    },
    {
      "name": "Web / Marketing Agency",
      "role": "Software company",
      "country": "Bangladesh",
      "image": "assets/logos/tork.webp",
      "service": "Video Editing + Graphic Design",
      "quote": "Ishtiak was an important part of our creative team, supporting us with both video editing and graphic design for our marketing efforts. He was able to understand our brand requirements and consistently create professional, visually appealing content. His creativity, responsiveness, and ability to work within deadlines made collaboration very easy. We were genuinely satisfied with the quality of his work."
    },
    {
      "name": "YouTube Sit-Down Content Creator",
      "role": "Bangladeshi Entrepreneur",
      "country": "Bangladesh",
      "image": "assets/images/testimonial_entrepreneur.webp",
      "service": "YouTube Video Editing",
      "quote": "Azmi did an excellent job editing our YouTube videos. He understood the style and tone of our sit-down content and made the videos more engaging without making the edits feel distracting. From pacing and cuts to overall presentation, everything was handled professionally. He was reliable, responsive, and easy to work with. I would definitely recommend his editing services to other content creators."
    },
    {
      "name": "Podcast Client",
      "role": "Podcast · Politician · News & media website",
      "country": "American-Bangladeshi",
      "image": "assets/logos/aalap.webp",
      "service": "Podcast Editing + Shorts/Reels",
      "quote": "I had a great experience working with him as our video editor. He did an excellent job with our podcasts and short-form content. He was creative, responsive, and understood our requirements really well. His work was always clean, engaging, and delivered on time. Highly recommended!"
    }
  ]
};
